"use client";

/**
 * Tap-to-talk fallback: zero-typing quick phrases answered via
 * /api/generate and read aloud by the parent. Pure presentation —
 * request state lives in the parent Companion component.
 */
import AiText from "@/components/AiText";
import type { PlanLanguage } from "@/lib/profile";

export const QUICK_PHRASES = [
  "I'm having a hard day",
  "I feel a craving coming",
  "Tell me something encouraging",
  "Help me get through the next hour",
  "I'm proud of something today",
  "I can't stop overthinking",
] as const;

export type ReplySource = "gemini" | "fallback";

interface CompanionChipsProps {
  notice: string;
  busyPhrase: string | null;
  reply: string;
  replySource: ReplySource | null;
  language: PlanLanguage;
  onPhrase: (phrase: string) => void;
}

export default function CompanionChips({
  notice,
  busyPhrase,
  reply,
  replySource,
  language,
  onPhrase,
}: CompanionChipsProps) {
  return (
    <section aria-label="Tap to talk" className="companion-fallback space-y-6">
      <div className="companion-intro glass overflow-hidden p-7 text-center sm:p-9">
        <div className="companion-kicker-row companion-kicker-row-centered">
          <p className="eyebrow">
            <span className="companion-kicker-dot" aria-hidden="true" />
            Tap-to-talk companion
          </p>
        </div>
        <h1 className="companion-title mt-2 text-3xl font-bold tracking-tight sm:text-4xl">
          What feels closest?
        </h1>
        <p className="companion-lede mx-auto mt-3 max-w-lg text-sm leading-relaxed text-muted sm:text-base">
          Choose a thought below. Pulari will answer out loud, so you never
          need to find the words.
        </p>
        {notice && (
          <p
            role="status"
            className="companion-notice mx-auto mt-5 max-w-lg rounded-2xl bg-surface-2 px-4 py-3 text-sm"
          >
            {notice}
          </p>
        )}
      </div>

      <div className="quick-phrase-grid grid gap-4 sm:grid-cols-2">
        {QUICK_PHRASES.map((phrase, index) => (
          <button
            key={phrase}
            type="button"
            onClick={() => onPhrase(phrase)}
            disabled={busyPhrase !== null}
            aria-busy={busyPhrase === phrase}
            className="quick-phrase-card glass lift animate-fade-up group flex min-h-20 items-center gap-4 px-5 py-4 text-left font-medium disabled:opacity-60"
            style={{ animationDelay: `${index * 55}ms` }}
          >
            <span className="quick-phrase-mark" aria-hidden="true">
              {busyPhrase === phrase ? "…" : "“"}
            </span>
            <span className="quick-phrase-copy flex-1">
              {busyPhrase === phrase ? "Thinking…" : phrase}
            </span>
            <span className="quick-phrase-arrow" aria-hidden="true">
              →
            </span>
          </button>
        ))}
      </div>

      {reply && (
        <article
          role="status"
          aria-live="polite"
          aria-atomic="true"
          data-source={replySource ?? "fallback"}
          className="companion-reply glass animate-fade-up p-6 sm:p-7"
        >
          <div className="companion-reply-heading">
            <span className="companion-reply-avatar" aria-hidden="true">
              P
            </span>
            <div>
              <p className="eyebrow">
                {replySource === "gemini"
                  ? "Generated live with Gemini"
                  : "Connection fallback"}
              </p>
              <span>
                {replySource === "gemini"
                  ? "Made for this moment"
                  : "Not generated by Gemini"}
              </span>
            </div>
          </div>
          <div className="companion-reply-body mt-4">
            {/* Fallback copy is English; only tag the language on real replies. */}
            <AiText
              text={reply}
              lang={replySource === "gemini" ? language : undefined}
            />
          </div>
        </article>
      )}
    </section>
  );
}
